services:
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: processos_juridicos
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
  camunda:
    image: camunda/camunda-bpm-platform:7.17.0
    ports:
      - "8081:8080"
