services:
  # Serviço da sua aplicação
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
      - camunda
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/processos_juridicos
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: password

  # Banco de Dados PostgreSQL da aplicação
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: processos_juridicos
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  # Camunda BPM
  camunda:
    image: camunda/camunda-bpm-platform:7.17.0
    ports:
      - "8081:8080"
    depends_on:
      - db

  # SonarQube para análise estática de código
  sonarqube:
    image: sonarqube:9.9.0-community
    container_name: sonarqube
    depends_on:
      - sonar-db
    environment:
      SONAR_JDBC_URL: jdbc:postgresql://sonar-db:5432/sonar
      SONAR_JDBC_USERNAME: sonar
      SONAR_JDBC_PASSWORD: sonar
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_logs:/opt/sonarqube/logs
    ports:
      - "9000:9000"

  # Banco de Dados para o SonarQube
  sonar-db:
    image: postgres:13
    container_name: sonar-db
    environment:
      POSTGRES_USER: sonar
      POSTGRES_PASSWORD: sonar
      POSTGRES_DB: sonar
    volumes:
      - sonar_postgresql:/var/lib/postgresql/data

volumes:
  db_data:
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_logs:
  sonar_postgresql:
