spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/processos_juridicos
    username: postgres
    password: password
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
flyway:
  enabled: true
  locations: classpath:db/migration

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
  info:
    title: "Attus - Sistema de Gerenciamento de Processos Jurídicos"
    description: "API para Gerenciamento de Processos, Partes e Ações no contexto jurídico."
    version: "1.0.0"


# Configuração do Camunda
camunda.bpm.admin-user:
  id: admin
  password: admin

# Configuração de logs para melhor depuração
logging:
  level:
    org.springframework: INFO
    org.camunda.bpm: DEBUG  # Aumentar a verbosidade dos logs do Camunda para depuração



# Configurações adicionais (se necessário)
server:
  port: 8080  # Porta padrão para o servidor
