spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/processos_juridicos
    username: postgres
    password: password
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
flyway:
  enabled: true
  locations: classpath:db/migration
